### ISSUE TITLE
Translation messages manager tool

### ISSUE THREAD

**Issue by Kureev** [formatjs/intl-messageformat#106]
Dear community,

I'm trying to find some web service like localeapp.com, webtranslateit.com, lingohub.com, transifex.com, oneskyapp.com, crowdin.net, phraseapp.com or whatever which supports export to ICU/CLDR format. For sure some of you should use something like this, but on the ones I mentioned above I wasn't able to find such kind of export. How you collaborate on translations?

P.S. Sorry for an offtopic, I know it's not related to library itself, but I don't know where to ask that kind of questions - I wasn't able to find an IRC or Slack channel, so that's why I'm asking it there.

**Comment by caridy** [comment]
@Kureev this is a very good question. There are two things:

1. first, translating ICU messages needed by your app:
For this one, we don't have an answer at the moment. Internally, at Yahoo, we do have a proprietary infrastructure to deal with all this, but we have no plans to open that up for all users. There are definitely firms that can provide this service (we use some professional translators that can deal with ICU messages), but I don't know if they provide nice hooks do facilitate the process.

2. second, extraction of messages from source code:
You can look at https://github.com/yahoo/react-intl/issues/89 for more details about some ideas on how to extract the messages from code. I think http://l10ns.org/ is the best tool I have tried.

Please, if you figure something out, let us know.

**Comment by Kureev** [comment]
@caridy I was talking about the first one. I really like the format and the way you've implemented it, but now I faced an issue that we need to have a tool for collaboration for translations as I mentioned before. I'm really amazed, that from all those solutions I wasn't able to find even 1 which supports ICU :(

**Comment by tschaub** [comment]
I'm just hitting the same issue.  We're interested in using the React FormatJS integration, but need the localization files to be in a format supported by a service like transifex.com.  Can anyone comment on where else the ICU format is used?  It would be unfortunate to commit to a syntax that translators aren't familiar with and no other service works with.

**Comment by LorbusChris** [comment]
a ICU to-from XLIFF converter would be useful if one wants to use third-party translation provider like transifex

**Comment by caridy** [comment]
@LorbusChris thanks for the suggestion. I will look into XLIFF when I get a chance.

**Comment by LorbusChris** [comment]
@caridy: There already are such converter by the icu-project (genrb for ICU to XLIFF and XLIFF2ICUConverter for XLIFF to ICU**4J**), written in Java though. However, this here might still be of some value: http://www.icu-project.org/repos/icu/icuhtml/trunk/design/locale/xliff-profile-icuresourcebundle-1.2.htm

**Comment by maxkoryukov** [comment]
@caridy: and now (at the end of 2016), there is a JS-converter from **ICU txt** [**bundle** format](http://userguide.icu-project.org/locale/resources) to **JSON** (and several other formats): https://github.com/alex-dow/icu-converter

> back ref: alex-dow/icu-converter#12

**Comment by maxkoryukov** [comment]
The same topic in `messageformat` repo : messageformat/messageformat.js#69

**Comment by jamuhl** [comment]
We now fully support icu format at https://locize.com (and plan to extend based on your feedback / demand):

- highlighting
- validation
- machine translations
- plural conversion between source and target language
- prettify of your icu strings

<img width="1152" alt="screen shot 2017-10-29 at 14 12 00" src="https://user-images.githubusercontent.com/977772/32144317-5b6ca10c-bcb7-11e7-82f9-da51b0a34c22.png">

Your feedback would be very welcome - also if someone could provide us with a file react-intl extracts we could look into supporting that for importing (beside xliff, json, ...)

**Comment by jarnoux** [comment]
Just leaving a solution that doesn't require human translators here: by using the translate example built by @ericf in react-intl, it's possible to send the string literals to amazon translate by just modifying the uppercase translator [here](https://github.com/yahoo/react-intl/blob/763f3fcbf87abc1a2a1021f684217f56bf8d4581/examples/translations/scripts/translate.js#L33).

**Comment by longlho** [comment]
closing due to stale, we also have a slack channel now :)
