### ISSUE TITLE
Can't use "console.log(error.stack)" on SyntaxError

### ISSUE THREAD

**Issue by slorber** [formatjs/intl-messageformat#107]
The SyntaxError does not have the stack property, but this property is often used in log statements inside libraries that we don't always have control on, or that we did develop assuming normal error properties.

It would be nice to support these attributes to make it easier to deal with react intl errors without having to rewrite our log statements.

**Comment by jasonmit** [comment]
I believe what you're referring to is an object formed downstream in https://github.com/pegjs/pegjs generated code https://github.com/pegjs/pegjs/blob/5e6b5da4e91790200f34efb9dce55103cd1aa261/lib/compiler/passes/generate-javascript.js#L780-L792

**Comment by slorber** [comment]
yes @jasonmit it seems there's already an issue for that!  https://github.com/pegjs/pegjs/issues/331

**Comment by caridy** [comment]
@slorber do you want to update your PR to just upgrade the dep?

**Comment by slorber** [comment]
@caridy I think the new version of PEG parser is not published to NPM yet

**Comment by caridy** [comment]
https://github.com/pegjs/pegjs/issues/357

**Comment by longlho** [comment]
fixed since we already upgraded pegjs
