### ISSUE TITLE
Add support for custom functions

### ISSUE THREAD

**Issue by Ndrou** [formatjs/intl-messageformat#132]
Hi !
It would be really useful to have the ability to define custom functions for improve the syntax.

e.g : 
`hello {anotherkey, functionName, arg1, arg2, arg3...}`

``` javascript
function functionName(arg1, arg2, arg3){
   return arg1 + arg2 + arg3;
})
```

I'm facing this situation when i want to implement nested translation (translation that contains a link to another translation), but i don't want to rewrite the integrality of the compiler :)

Have a good day !

**Comment by caridy** [comment]
most templating languages will allow you to do so by executing helpers or arbitrary functions, and the result is what you pass into the message. If the value is a number and needs to be formatted, you have the custom formatters that allow you to customize some aspects of the formatting process, but I will be reluctant to add anything that is not part of ICU message format.
