### ISSUE TITLE
Provide fallback for browsers without native Intl or Intl polyfill

### ISSUE THREAD

**Issue by aaronshaf** [formatjs/intl-messageformat#140]
Many of us are only using simple messages. It would be nice not to have to provide the polyfill in these kinds of situations on Safari for now.

**Comment by hey99xx** [comment]
I'm also curious if this library would crash in runtime if you have the simple messages. If I have only plural rules and no number/date/formatters, can I get away without using Intl polyfill?

**Comment by caridy** [comment]
this is not a polyfill, but a library since browsers are not implementing messageformat, nor there is a proposal for doing so.

maybe another library that does similar things without the overhead will be enough for small projects.
