### ISSUE TITLE
Support "optional" parameters?

### ISSUE THREAD

**Issue by slorber** [formatjs/intl-messageformat#143]
Hi,

My popup sometimes need to have title "Duplicate" and sometimes "Duplicate in {folderName}"

I'd like to do something like that:

``` javascript
        <FormattedMessage
          id={"popup.title"}
          values={{folderName: preSelectedFolder ? preSelectedFolder.name : undefined}}
        />
```

And in my message, something like `"popup.title": "Duplicate {folderName ? folderName : ""}"`

This is something I often want to do and by searching the doc multiple times I never found an elegant way to do it. Wouldn't it be nice to support it (probably not the syntax I shawn but you get the idea).

The workaroud seems to be something like:

``` javascript
        <FormattedMessage
          id={"popup.title"}
          values={{folderName: preSelectedFolder ? preSelectedFolder.name : "NONE"}}
        />
```

and

```
Duplicate {folderName, select,
    NONE {}
    other {in {folderName}}
}
```

which is a bit unnatural and error prone

**Comment by ericf** [comment]
Yeah I can see how this would be annoying. I'm not aware of how ICU handles this case, but if they have something we can copy it. The problem with making things optional is people forgetting to provide values and having a string that doesn't make sense to the user. The way I've seen this handled is having two strings and determining which to format based on the values you have.
