### ISSUE TITLE
Mustache (and Backbone) integration

### ISSUE THREAD

**Issue by KrzysztofMadejski** [formatjs/intl-messageformat#145]
Is anyone working on one?

**Comment by KrzysztofMadejski** [comment]
The boy has a name ;)

**Comment by KrzysztofMadejski** [comment]
I've did Mustache integration of intl-messageformat in Backbone-based Recline library. There is no Backbone related code, just:
- Mustache translation tags, ie. `{{t.Add_row}}`
- Loading and caching translations
- Language resolution

The code is contained in this pull request: https://github.com/DanePubliczneGovPl/ckanext-danepubliczne/commit/f01a851dc7f67e85ee760c1b621610b09759ff01

Relevant for standalone library are:
- [main code](https://github.com/DanePubliczneGovPl/recline/blob/921be798846d19bfea186d7b0c7874a0971de5b2/vendor/common-intl-wmustache.js)
- [tests (QUnit)](https://github.com/DanePubliczneGovPl/recline/blob/921be798846d19bfea186d7b0c7874a0971de5b2/test/view.i18n.test.js)
- [documentation](https://github.com/DanePubliczneGovPl/recline/blob/921be798846d19bfea186d7b0c7874a0971de5b2/docs/views.markdown) (scroll down to Internationalization section)

I'd be more than happy if anyone would like to pack it as a proper npm library.

To give you an quick overview (it's an excerpt from documentation):

Translation tags in templates:
```
// will show "Add row" in defaultLocale (English) 
$template_simple_tag = '{{t.Add_row}}'; 
// will show "no records", "1 record" or "x records" in defaultLocale (English) 
$template_complex_tag = '{{#t.num_records}}{recordCount, plural, =0 {no records} =1{# record} other {# records}}{{/t.num_records}}'; 
```

And to make it work:
```
recline.View.translations['pl'] = {
     Add_row: 'Dodaj wiersz'
};

my.MultiView = Backbone.View.extend({
  render: function() {
    var tmplData = this.model.toTemplateJSON();
    tmplData = I18nMessages('recline', recline.View.translations).injectMustache(tmplData);  // inject Moustache formatter
    var output = Mustache.render(this.template, tmplData);
    ...
  }    
});
```

How do you like it?

**Comment by longlho** [comment]
this is out of scope for this library
