### ISSUE TITLE
Need default format for time Type

### ISSUE THREAD

**Issue by cwtuan** [formatjs/intl-messageformat#157]
```"Coupon expires at {expires, time, medium}"``` outputs ``` "Coupon expires at 5:08:33 PM"```

But ```"Coupon expires at {expires, time}"``` outputs ```"Coupon expires at 4/7/2017"```

If the ```format``` is missing, should it have default one?

**Comment by longlho** [comment]
it follows the default behavior of `Intl.DateTimeFormat`
