### ISSUE TITLE
Support datetime type

### ISSUE THREAD

**Issue by cwtuan** [formatjs/intl-messageformat#158]
The types include ```time``` and ```date```, but it doest not support ```datetime``` format
For example,  ```"Coupon expires at {expires, datetime}"``` are supposed to be ```"Coupon expires at 4/13/2017 22:33:50"```

**Comment by cwtuan** [comment]
Any idea?

**Comment by longlho** [comment]
You can define a custom format using the options from `Intl.DateTimeFormat`

**Comment by cwtuan** [comment]
@longlho any example?
