### ISSUE TITLE
Allow passing date param in string format

### ISSUE THREAD

**Issue by felicienfrancois** [formatjs/intl-messageformat#166]
The following code currenctly throw a "Provided date is not in valid range." error
```javascript
new IntlMessageFormat("{test, date, short}").format({
  test: "2017-07-20"
});
```

yyyy-mm-dd format for date is quite common in json and is supported by Date constructor.
I would expect it to work seemlessly with messageformat.

The current behavior prevent the use of json objects in message data without rewriting date values.

The fix would be to parse the value to a date before passing it to Intl.DateFormat.
Using the Date constructor seems the easiest way to do it.

**Comment by longlho** [comment]
Parsing date string into `Date` is a whole other can of worms and different browsers do it very differently. I don't think we want to necessarily do input parsing in the lib, as the spec for `Intl.DateTimeFormat` is pretty clear
