### ISSUE TITLE
ES6 module for browser

### ISSUE THREAD

**Issue by brettz9** [formatjs/intl-messageformat#174]
Can you provide an export format such that browsers like Chrome which now support ES6 modules natively can take advantage of them with a modular import?

~Your source files do not work (at least due to lacking the ".js" extension).~ _I see now that you do support `js:next:main`, but it appears from https://github.com/rollup/rollup/wiki/pkg.module , that `module` is to be preferred._

Another ideal here would be to allow genuinely modular (and synchronous) loading of locale data too. 

(Since synchronous XHR is deprecated, browser modules depending on IntlMessageFormat that wish to be available synchronously cannot do this (and it would require content-policy-restricted `eval` anyways).)

Thanks!

**Comment by brettz9** [comment]
Another ideal here would be to allow genuinely modular loading of locale information too. 

(Since synchronous XHR is deprecated, browser modules depending on IntlMessageFormat that wish to be available synchronously cannot do this (and it would require content-policy-restricted `eval` anyways).)

**Comment by longlho** [comment]
fixed in #188

**Comment by brettz9** [comment]
Great! Might you add an example on how to do the modular import, including locale loading?
