### ISSUE TITLE
How can I output the 24 hour time format (14:00 instead 2:00 PM)?

### ISSUE THREAD

**Issue by pystone** [formatjs/intl-messageformat#177]
I want to output a time using 24 hour time format and I cannot do that with IntlMessageFormat. I tried to give a locale where 24 hour is more popular (e.g. zh-CN) but it still outputs a 12 hour time format. 

I read this [page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat) and found that `DateTimeFormat` supports either `hc` in `locale` or `hour12` in `options`. However, `hc` is not working as I expected and I find no way to input `options`.

How am I supposed to do it?

**Comment by kumarharsh** [comment]
Can you share the code you tried with?

```js
const IntlMsgFmt = require('intl-messageformat');
new IntlMsgFmt(
  '{userDate, time, custom}', // your message
  'zh-CN', // locale
  { time: { custom: { hour: "2-digit", minute: "2-digit" } // options
}}).format({userDate: new Date()})
```
gives me

```
17:21
```

**Comment by longlho** [comment]
stale
