### ISSUE TITLE
Causing crash in production environment

### ISSUE THREAD

**Issue by TiagoPortfolio** [formatjs/intl-messageformat#181]
Context: React app in development mode

If a message is provided as an Object, only a warning is logged into the console:
`throw new TypeError('A message must be provided as a String or AST.');` _(in src/core.js)_

First I ignored this error because the app was not crashing.
When I deployed the app in production mode, my app was crashing because React doesn't accept children as Object.

Please, besides the warning, make the app crash in development mode. To do this, stop using the defaultMessage in development mode when this happens.

**Comment by longlho** [comment]
We will continue to use `defaultMessage` since there's typically a deployment/translation lag between src & strings being translated

**Comment by TiagoPortfolio** [comment]
I am not sure if you guys understood the problem...

Instead of handling correctly the `TypeError` and returning a warning and/or an empty string, you guys prefer to cause a crash in **production** mode?

**Comment by longlho** [comment]
The problem you're talking can easily be caught at compile time instead of runtime.
