### ISSUE TITLE
How to define default value for context variables?

### ISSUE THREAD

**Issue by Victorien-Tardif** [formatjs/intl-messageformat#182]
### FEATURE REQUEST

When defining context variables, I'd like to define a default value if value is not passed.
Let's say I have a message `{count, plural, zero {no items} one {one item} many {many items}}`, I would like to be able to define a default value, like `{count, plural, zero {no items} one {one item} many {many items}} default {items}` so that I could use it this way:

### Expected behavior
```
const messages = defineMessages({
   items: '{count, plural, zero {no items} one {one item} many {many items}} default {items}',
});

const messageWithDefinedValue = formatMessage(messages.items, { count: 1 });
console.log(messageWithDefinedValue); // one item

const messageWithUndefinedValue = formatMessage(messages.items);
console.log(messageWithUndefinedValue); // items
```

### Current behavior
```
const messages = defineMessages({
   items: '{count, plural, zero {no items} one {one item} many {many items}} default {items}',
});

const messageWithDefinedValue = formatMessage(messages.items, { count: 1 });
console.log(messageWithDefinedValue); // one item

const messageWithUndefinedValue = formatMessage(messages.items);
console.log(messageWithUndefinedValue); // Error: The intl string context variable 'count' was not provided
```

**Comment by longlho** [comment]
I think this is out of scope for this library, you can also use `other` as the fallback

**Comment by wparrott-touchnet** [comment]
I think default values have a broader application than just plurals. For example, if you want to check an arbitrary string to make sure it's not empty, null, or undefined. Something along these lines:

```
{
    id: "messageWithDefault",
    defaultMessage: `"default" :: "{foo, select,
        =undefined {default}
        =null {default}
        ="" {default}
        other {{foo}}
    }"`,
}
```

I can create a separate issue if you think my use case is different than OP, but I think they are roughly the same idea.

[CodeSandbox example](https://codesandbox.io/s/ecstatic-hermann-5hln4?fontsize=14)
