### ISSUE TITLE
3.0 - TypeError: Cannot read property 'parse' of undefined

### ISSUE THREAD

**Issue by sqal** [formatjs/intl-messageformat#189]
Hi. I updated today intl-messageformat to 3.0 from 2.2.0 but I ran into mentioned issue.

```terminal
core.js:148 Uncaught TypeError: Cannot read property 'parse' of undefined
    at eval (core.js:148)
```

Do you have any idea what might be wrong here? I created minimal reproduction for you so you can see what's going on.

### steps to reproduce
- Clone https://github.com/sqal/intl-messageformat-bug-repro
- `npm i && npm run serve`
- Open the site at http://localhost:8080/ and look at the console logs

Thank you for looking into this :)

**Comment by longlho** [comment]
thanks a lot for reporting. I'll take a look asap

**Comment by macca16** [comment]
This is the same issue as https://github.com/formatjs/formatjs/issues/7 I believe

**Comment by tirithen** [comment]
Same error here, I can compile the package in my project same as before with webpack:

    import IntlMessageFormat from 'intl-messageformat';

But I get the same error when loading the page:

    core.js:148 Uncaught TypeError: Cannot read property 'parse' of undefined
        at Object../node_modules/intl-messageformat/lib/core.js (core.js:148)
        at __webpack_require__ (bootstrap:19)
        at Object../node_modules/intl-messageformat/lib/main.js (main.js:4)
        at __webpack_require__ (bootstrap:19)
        at Object../node_modules/intl-messageformat/index.js (index.js:5)
        at __webpack_require__ (bootstrap:19)
        at Module../utils/Localizer.js (Localizer.js:1)
        at __webpack_require__ (bootstrap:19)

**Comment by longlho** [comment]
Can you give `3.1.0` a try?

**Comment by tirithen** [comment]
Wow, that was fast feedback for me, and yes now it works as well as 2.2.0 without changes in my other code.

**Comment by longlho** [comment]
thanks for verifying. Closing this issue as fixed then
