### ISSUE TITLE
No bower install for intl-messageformat

### ISSUE THREAD

**Issue by triptych** [formatjs/intl-messageformat#57]
Going through the documentation for the Intl quickstart (https://github.com/yahoo/js-intl-docs/blob/master/quickstart-browser.md )
It says to install via bower:

bower install handlebars-helper-intl which is supposed to pull in `handlebars-helper-intl`, `intl-messageformat`, and `handlebars`. However it only pulls in `handlebars-helper-intl`, and I think this is in part due to there not being a bower install for `intl-messageformat`

When I run this manually:

`bower install intl-messageformat`

I get: 

`bower                        ENOTFOUND Package intl-messageformat not found`

**Comment by renan** [comment]
Seems like someone forked this repository and registered their fork on bower:

https://github.com/brettz9/intl-messageformat
