### ISSUE TITLE
refactor cldr data collector

### ISSUE THREAD

**Issue by caridy** [formatjs/intl-messageformat#71]
## Locales

This pkg only consume root locales. This means we don't care (maybe we should jejejeje), about `fr-FR`, or `en-BR`, we only care about `en` and `fr` as the top level locales. The routine to analyze all locales in CLDR and pick up the root locales is here:
https://github.com/yahoo/intl-messageformat/blob/master/tasks/build-data.js#L7-L16
## Plural rules extraction

This pkg uses `cldr.extractPluralRuleFunction()` to collect "a function" that contains the pluralization and gender rules:
https://github.com/yahoo/intl-messageformat/blob/master/tasks/build-data.js#L98

This is where things gets funky, because we will like to collect data instead and creating the logic around the data rather than a function that we don't know how it works. The content of that function is something along these lines:

``` javascript
// require('cldr').extractPluralRuleFunction('en') returns:
function anonymous(n) {
  var i=Math.floor(Math.abs(n)),
        v=n.toString().replace(/^[^.]*\\.?/,"").length;
  if (typeof n==="string") n=parseInt(n,10);
  if (i===1&&v===0) return"one";
  return"other"
}
```

**Comment by ericf** [comment]
Improvements to the locale data are in PR #102

**Comment by longlho** [comment]
close since we use `Intl.PluralRules` now
