### ISSUE TITLE
Figure out how to collab with messageformat.js

### ISSUE THREAD

**Issue by SlexAxton** [formatjs/intl-messageformat#72]
Seems like we're looking for the same ends. Hadn't realized that this was based off of my peg, which makes it even easier to collab.

What are the blockers?

**Comment by SlexAxton** [comment]
Jumping back into this thread. I recently had to setup a new internationalizable app in ember, and it made so much sense to just use ember-intl. It's got date and number/currency stuff in there as well as messageformatting. I've had a pretty good go at it, and it's working well. Thanks!

That said, I still kind of wanted to use the messageformat.js implementation of MessageFormat for some of our newer features/speed/precompilation-ability/i-wrote-it-so-it-feels-weird. I of course didn't, because that'd be ridiculous, but it made we wonder if you folks were interested in consuming it downstream?

We're happy to allow a relicense/sign-something to make yahoo-legal folks happy, if that's a concern. We are gaining tests on edge-cases and added explicit support for selectordinal/decimals/shorthand since our two implementations have existed. We've got a good system for pulling in latest CLDR data automatically with [make-plural](https://github.com/eemeli/make-plural.js). And we've got the beginnings of tools to help with translation (and would like to focus on building more things in this direction). We're also happy to rebase on top of the messageformat-parser stuff (but would probably require some updates for our newest features).

I just always dislike situations when there are multiple good implementations of the same thing with slight variances in support/updates/compatibility. If there's any way we can join forces, I think it'd be better for everyone, as well as making sure the 402 standardization process has maximum implementation testers. I know globalize.js is pulling us in to do a similar thing, so we're happy to play more of a dependency role like this (even if `intl-messageformat` still explicitly existed, pulled in `messageformat` as a dependency, modified the API in the way that was best, and shipped the wrapper).

What would you guys need to see from messageformat.js to make this desirable for format (I know precompiling was a turn-off, for instance)? Totally cool if you'd rather keep on with the current setup, I just figured I'd throw this out for collaboration's sake. Also happy to talk more privately about it over email or something if github issues is not ideal.

**Comment by ericf** [comment]
> Also happy to talk more privately about it over email or something if github issues is not ideal.

I think we should just have a higher bandwidth conversation in person or over video to discuss this, and then we can put the notes back into this thread. Let's try to get something going for this week since @caridy will be going on a long vacation soon.

**Comment by SlexAxton** [comment]
Happy to do so: alexsexton@gmail.com - free most days during the day, with rare exceptions. Send me an invite for something that works for ya'll?

**Comment by morficus** [comment]
I was just comparing the 2 libs to figure out which one to use in my up coming (node) project.
I'm SO GLAD to see that there is a desire to collaborate and that this thread is still active (even tho it started about 7 months ago).

Really looking forward to this :tada: :smile:

**Comment by glen-84** [comment]
Any news on the collaboration?

**Comment by ericf** [comment]
@glen-84 the focus is collaborating at the standards level. Recently we've been working to get the lower level pieces in place like exposing abstract locale operations, plural rules, and `formatToParts`: https://github.com/tc39/ecma402

**Comment by glen-84** [comment]
That's cool. It'll be great to have these APIs available in browsers (and in Node).

**Comment by GCheung55** [comment]
> I'm SO GLAD to see that there is a desire to collaborate and that this thread is still active (even tho it started about 7 months ago).

I'm glad to see collaboration happening too! I'm about to begin an Ember.js project and plan on using ember-intl. One of the concerns my team has with using ember-intl is a missing precompile step.

Please reconsider the decision to leave out a precompiler.

**Comment by longlho** [comment]
close due to stale
