### ISSUE TITLE
Is there something like xgettext to extract original phrases from a source code?

### ISSUE THREAD

**Issue by koorchik** [formatjs/intl-messageformat#94]
With gettext (ngettext) it is very easy to do I18N. 
1) I just run xgettext, it collects all the phrases in a source code and saves them to PO file
2) I send the PO file to a translater who uses "poedit" to add translations.
3) I convert translated PO to JSON and use JSON in my app.
4) If any of the original English phrases were changed, I just run "xgettext" once more. It updates existing PO file marking changed phrases and adding new ones.  Then I repeat from step "2".

intl-messageformat is a good alternative to gettext and ngettext. But how to extract English phrases from source code? Do you have something similar to xgettext?

**Comment by caridy** [comment]
No, we don't. We do want to provide some guidelines on how to deal with the actual translations, but unfortunately the internal systems we use at yahoo to do so are proprietary. We were planning to create an example using some of the ideas behind l10ns project (http://l10ns.org/docs.html) but we haven't get a chance to do so.

**Comment by koorchik** [comment]
Thanks. l10ns approach looks interesting. It would be great to have something like "l10ns update" and "l10ns interface".

**Comment by longlho** [comment]
You can now do that using either https://github.com/formatjs/babel-plugin-react-intl or https://github.com/longlho/ts-transform-react-intl
