### ISSUE TITLE
Format array of values to sentence

### ISSUE THREAD

**Issue by rlivsey** [formatjs/intl-messageformat#99]
(this might not be the right place to post this, feel free to close & point me elsewhere)

I've a list of values which should be displayed as a sentence, eg: `['one', 'two', 'three']` should output `one, two and three`. 

I'm not sure if this is possible with the ICU message format, or whether it's a higher level problem out of scope of this project?

I don't see an example of this kind of format in the ICU docs or elsewhere, but it seems like it would be a fairly common problem.

**Comment by ericf** [comment]
This is supported, but you must use numeric argument names in the message, e.g:

```js
var msg = 'The message has: {0}, {1}, and {2} values.';
var mf = new IntlMessageFormat(msg);
console.log(mf.format(['one', 'two', 'three']));
// => 'The message has: one, two, and three values.'
```

Is this what you mean? If not, could you provide a more detailed example of what you're trying to do?

**Comment by nfroidure** [comment]
I think @rlivsey meant it to be used with an arbitrary amount of items.

**Comment by ericf** [comment]
@nfroidure @rlivsey okay, then can you provide more details on what you're trying to do with an example message and expected output?

**Comment by rlivsey** [comment]
Is it possible with an unknown/arbitrary number of items? (@nfroidure exactly)

One use-case I currently have is displaying some selected days of the week, in this case I know there's a max of 7 options but in other situations it's an unbounded list which the user could generate.

Eg given an array of days / any other values, I'd want to generate:

* ['Friday'] -> "Friday"
* ['Monday', 'Friday'] => "Monday and Friday"
* ['Sunday', 'Monday', 'Friday'] => "Sunday, Monday and Friday"

I could build a higher level helper much like [to_sentence in Rails](http://apidock.com/rails/ActiveSupport/CoreExtensions/Array/Conversions/to_sentence), and store the separator and other options in the locale, which by the sounds of it is probably the way to go if this kind of thing isn't in the core lib.

**Comment by rlivsey** [comment]
Another example would be Slack's email access message when logging in. which displays a message like:

"If you have an @foo.com, @bar.com or @baz.com email address, you can create an account."

Currently in order to do that I'm having to convert the domains to a sentence externally and then my message format is simply: 

"If you have an {domainSentence} email address, you can create an account."

It would be nice to be able to have that all inline somehow:

"If you have an {domainSentence, array, sentence} email address, you can create an account."

**Comment by ericf** [comment]
I checked the CLDR data and we have this information available.

Interesting enough the ICU project mentions a TODO to propose an API, code, and tests for the Java and C implementations. I would be for adding this feature to either this package directly, or another `intl-listformat` package (maybe?)

Here's the `listPatterns` data for English:

```xml
<listPatterns>
	<listPattern>
		<listPatternPart type="start">{0}, {1}</listPatternPart>
		<listPatternPart type="middle">{0}, {1}</listPatternPart>
		<listPatternPart type="end">{0}, and {1}</listPatternPart>
		<listPatternPart type="2">{0} and {1}</listPatternPart>
	</listPattern>
</listPatterns>
```

**Comment by rlivsey** [comment]
That would be fantastic. In the meantime I've added a `to-sentence` helper and am "sentencifying" content before passing it into the message formatter.

**Comment by rlivsey** [comment]
For anyone else stumbling on this issue, there's work going on to specify a list formatting API here: https://github.com/tc39/ecma402/issues/33

**Comment by longlho** [comment]
closing since `Intl.PluralFormat` is released and there's still no ICU spec for list formatting
